### ISSUE TITLE
Thread Manager

### ISSUE THREAD

**Issue by PierreBougon** [PierreBougon/ExistenZIA#2]
## ThreadManager:
- Changer le `std::unique_ptr<Task> getResult()` en `bool getResult(std::unique_ptr<Task> &out)` et enlever la méthode `bool hasResult()`. La méthode retourne true si il y a eu un résultat et l'a placé dans le unique_ptr, sinon elle retour false.

**Comment by PierreBougon** [comment]
- `getResult()` return une task il serait plus intuitif de l’appeler `getTaskDone()`

- `addtask()` prends une request et un client, je pense que ce n'est pas à la threadPool de créer les tasks et que donc il faut lui passer une task qui contient déja ses informations soit `addTask(unique_ptr<ATask>)` quelque chose comme ça

- Dans le même sens `hasResult()` peut devenir `hasTaskDone()` ou `hasTaskFinished()` sinon il faut set une callback

- Je ne vois pas dans quel cas on a besoin du ModuleManager dans la threadPool

**Comment by MarcBrout** [comment]
- voir mon premier point
- ok pour moi
- voir mon premier point
- le ModuleManager contient les module shared, il doit donc être passé au modules qui tournent dans les threads afin de pouvoir les appeller (#logger)

**Comment by PierreBougon** [comment]
Du coup on est d'accord sur les trois premiers points, pour le dernier point je ne sais pas mais si on reste sur ça on garde seulement une ref sur le ModuleManager il faut donc pouvoir le set avec un setter

**Comment by puillandre** [comment]
le moduleManager servait dans la création de Task: si le threadManager ne le fait plus, il n'y a plus besoin du moduleManager.
Dans tous les autres cas, il n'y a jamais besoin de set le moduleManager: il est unique et n'est pas sensé bouger.

**Comment by MarcBrout** [comment]
- Comment voulez vous passer le module manager aux threads ? Il doit être présent lors de la création de ceux-ci qui se font dans le constructeur du AThreadManager. 
- Il n'est peut-être cependant pas nécessaire de le stocker si le ThreadManager n'est plus responsable de la création des nouvelles Tasks (du coup créer un TaskManager ? et refactorer la méthode `addTask(...)`)
