### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by PierreBougon** [PierreBougon/ExistenZIA#3]
## Loader
- Supprimer les méthodes `std::string getCoreField(std::string &field)` et `std::string getModuleField(std::string &field)`, elles ne sont plus nécessaires depuis l'ajout des maps je pense.
- Refactor de la méthode `void loadModule(std::string name)` en `void loadModule(std::string file, std::string entrypoint)`

**Comment by MarcBrout** [comment]
Pour le 2ème point:
Si ces informations sont dans la config du module il n'y a alors peut-être pas besoin de renommer la fonction

**Comment by puillandre** [comment]
Le path est dans la config du core: mais il faut ajouter une string path dans le loader, et un moyen de la set

**Comment by MarcBrout** [comment]
Du coup, on a un dossier avec tous les dll, ou chaque dll à son chemin d'accés ? Il faut être aussi capable de spécifier un entrypoint non ? où nos seuls entrypoints sont `config()` et `process()`...

**Comment by PierreBougon** [comment]
Le sujet dit qu'il est interdit d'avoir un path hardcoded donc il semble qu'on soit obligé d'avoir un path par dll

**Comment by puillandre** [comment]
-process est pas un entry point, (mais config oui).
-le path n'est pas hardcoded s'il se trouve dans le fichier de config du core, même s'il n'y en a qu'un seul. Dans un programme logique, les plugins se trouvent bien dans un même dossier non ?

**Comment by PierreBougon** [comment]
Ah oui dans ce cas je pense qu'on rentre dans le cadre du sujet en effet
Pour les entrypoint du coup on a dit qu'on loadait les différents modules à la config dans la pool de ModuleModel et qu'ensuite on fait des clones de ces models
Du coup entrypoint à la config seulement

**Comment by MarcBrout** [comment]
nodejs gère ses modules dans des dossiers séparés
