### ISSUE TITLE
ADataStorage

### ISSUE THREAD

**Issue by ZenoxTek** [PierreBougon/ExistenZIA#5]
In the class ADataStorage we set add of different type into the vector datas. But there is an issue when we get different value, we don't specify the index of the element we want to get. 
Did we add a parameter 'int index" to all getter ?

**Comment by MarcBrout** [comment]
## Solutions:
- Change the vector to a map, and associate datas to string keys (then refactoring the function to support that)
- Add an index, and the user has to remember which index to which info
- Let it that way, and the user has to depop front data in the same order he putted them in the vector

**Comment by ZenoxTek** [comment]
If we create a map, it's more logical to getTheData with the specific key and not an Index.

So we can add data with two arguments, The data & the string key

**Comment by puillandre** [comment]
Prefer the first solution, since the module with data to use don't "know" if another module add some data.

**Comment by MarcBrout** [comment]
Ok let's go for the map

**Comment by PierreBougon** [comment]
Seems to be a good way to get data from DataStore but what about boost::variant ?

**Comment by puillandre** [comment]
variant will replace the DataValue (since a union is not possible with a string). DataStore will have a map of string and variant

**Comment by PierreBougon** [comment]
DataStore will be a single map then ?

**Comment by MarcBrout** [comment]
in fact, it works with a String, the data will store the reference to the object that shall still be existing when the targeted module require it. But I think variant is more robust

**Comment by PierreBougon** [comment]
No string is not a pod type it's described in the [boost::variant doc](http://www.boost.org/doc/libs/1_64_0/doc/html/variant.html)

**Comment by MarcBrout** [comment]
putting [boost::any](http://www.boost.org/doc/libs/1_61_0/doc/html/any.html#idp39027120) that is similar to variant

**Comment by PierreBougon** [comment]
This issue is now obsolete due to PR #6
